<a href="https://colab.research.google.com/github/JessePMelo/FlightOnTime-Previs-o-de-Atrasos-de-Voos/blob/main/cancelamentos_de_voos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bibliotecas usadas

In [2]:
import pandas as pd

Montando drive para subir os arquivos !

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Abrindo arquivos

In [18]:
import pandas as pd

path_anac = "/content/drive/MyDrive/Datasets Hackaton/Voos Regulares Ativos - Anac/VRA_20211.csv"

df_anac = pd.read_csv(
    path_anac,
    sep=';',
    encoding='utf8',
    header=1
)

df_anac.head()

,ICAO Empresa Aérea,Número Voo,Código Autorização (DI),Código Tipo Linha,ICAO Aeródromo Origem,ICAO Aeródromo Destino,Partida Prevista,Partida Real,Chegada Prevista,Chegada Real,Situação Voo,Código Justificativa
0,TAM,3447,0,N,SBGR,SBFI,2021-01-09 20:25:00,2021-01-09 20:21:00,2021-01-09 22:05:00,2021-01-09 21:56:00,REALIZADO,NaN
1,TAM,3447,0,N,SBGR,SBFI,2021-01-10 20:25:00,2021-01-10 20:24:00,2021-01-10 22:05:00,2021-01-10 21:55:00,REALIZADO,NaN
2,TAM,3447,0,N,SBGR,SBFI,2021-01-11 20:25:00,2021-01-11 20:27:00,2021-01-11 22:05:00,2021-01-11 21:58:00,REALIZADO,NaN
3,TAM,3447,0,N,SBGR,SBFI,2021-01-12 20:25:00,2021-01-12 20:24:00,2021-01-12 22:05:00,2021-01-12 21:58:00,REALIZADO,NaN
4,TAM,3447,0,N,SBGR,SBFI,2021-01-13 20:25:00,2021-01-13 20:16:00,2021-01-13 22:05:00,2021-01-13 21:48:00,REALIZADO,NaN

In [19]:
df_anac.shape
df_anac.columns

Index(['ICAO Empresa Aérea', 'Número Voo', 'Código Autorização (DI)',
       'Código Tipo Linha', 'ICAO Aeródromo Origem', 'ICAO Aeródromo Destino',
       'Partida Prevista', 'Partida Real', 'Chegada Prevista', 'Chegada Real',
       'Situação Voo', 'Código Justificativa'],
      dtype='object')

Deixando só as colunas essenciais

In [22]:
df_colunas_essenciais = df_anac[[
      "ICAO Empresa Aérea",
      "ICAO Aeródromo Origem",
      "ICAO Aeródromo Destino",
      "Partida Prevista",
      "Partida Real",
      "Situação Voo"
]]

Deixando somente os voos realizados

In [24]:
df_voos_realizados = df_colunas_essenciais[df_colunas_essenciais["Situação Voo"] == "REALIZADO"]

Conferindo

In [26]:
df_voos_realizados.shape
df_voos_realizados.head()

,ICAO Empresa Aérea,ICAO Aeródromo Origem,ICAO Aeródromo Destino,Partida Prevista,Partida Real,Situação Voo
0,TAM,SBGR,SBFI,2021-01-09 20:25:00,2021-01-09 20:21:00,REALIZADO
1,TAM,SBGR,SBFI,2021-01-10 20:25:00,2021-01-10 20:24:00,REALIZADO
2,TAM,SBGR,SBFI,2021-01-11 20:25:00,2021-01-11 20:27:00,REALIZADO
3,TAM,SBGR,SBFI,2021-01-12 20:25:00,2021-01-12 20:24:00,REALIZADO
4,TAM,SBGR,SBFI,2021-01-13 20:25:00,2021-01-13 20:16:00,REALIZADO